title: Robotický Battle na Alejovej
author: Robotický Battle na Alejovej
email: galejeteam@gmail.com
logo_text: /img/logo_text.svg
description: >
  Webpage for RBA

plugins:
  - jekyll-feed
  - jekyll-polyglot

sass:
  style: compressed

permalink: /:categories/:year/:title:output_ext

exclude: [docker-compose.yml, scripts, vendor, Gemfile*, README.md]


languages: ["sk", "en"]
default_lang: "sk"
exclude_from_localization: ["assets", "img", "feed.xml"]
parallel_localization: true


defaults:
  - scope:
      path: "pdf/rules/racing"
    values:
      rules_racing: true
  - scope:
      path: "pdf/rules/vlastny_model"
    values:
      rules_model: true
  - scope:
      path: "pdf/rules/roboticka_vyzva"
    values:
      rules_vyzva: true
  - scope:
      path: "pdf/schedules"
    values:
      schedule: true
  - scope:
      path: "pdf/rules/common"
    values:
      common: true
  - scope:
      path: "pdf/directives"
    values:
      directive: true
